footer
Ivan011001/team-proj pull request #5
Opened 2023-05-06 07:47 UTC by Vitaliy1803

2023-05-06 07:59 UTC, Ivan011001 requested changes

2023-05-06 07:59 UTC, Ivan011001 commented on src/css/footer.css
> +    padding-bottom: 20px;
width: 100%, аби background-color був на усю ширину екрану

2023-05-07 08:50 UTC, Vitaliy1803 commented on src/css/footer.css
> +    padding-bottom: 20px;
FIXED!
Зробив! Але, я зпозиціонував блоки з ссилками на сторінки і соцмережі через position: absolut. Ввечрі спробую зробити через flex)) Але зараз все, здається, працює!

2023-05-07 08:56 UTC, Ivan011001 approved these changes

2023-05-07 08:56 UTC, merged